name: small-games
maintainer: "ashkan.kh.nazary@gmail.com"

dependencies:
  - base >= 4.7 && < 5
  - containers
  - array
  - wai-extra
  - yesod-core
  - yesod-eventsource
  - text
  - aeson
  - conduit
  - conduit-extra
  - binary
  - bytestring
  - stm
  - random
  - uuid
  - http-conduit
  - resourcet
  - attoparsec
  - mtl
  - gloss

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints
  - -Wmissing-methods
  - -threaded

library:
  source-dirs: lib

executables:
  # tic-tac-toe:
  #   main: tic-tac-toe.hs
  #   source-dirs: app
  #   dependencies:
  #     - small-games

  # rock-paper-scissors:
  #   main: rock-paper-scissors.hs
  #   source-dirs: app
  #   dependencies:
  #     - small-games
      
  # server:
  #   main: server.hs
  #   source-dirs: app
  #   dependencies:
  #     - small-games

  # gloss-client:
  #   main: gloss-client.hs
  #   source-dirs: app
  #   dependencies:
  #     - small-games
      
  # tetris-client:
  #   main: tetris-client.hs
  #   source-dirs: app
  #   dependencies:
  #     - small-games

  minesweeper:
    main:                Main.hs
    source-dirs:         MineSweeper
    
  sevent-segment-display:
    main:                Main.hs
    source-dirs:         SevenSegmentDisplay
    
  snake:
    main:                Main.hs
    source-dirs:         Snake  