name: small-games
maintainer: "ashkan.kh.nazary@gmail.com"

dependencies:
  - base >= 4.7 && < 5
  - containers
  - wai-extra
  - yesod-core
  - yesod-eventsource
  - text
  - aeson
  - conduit
  - conduit-extra
  - binary
  - bytestring
  - stm
  - random
  - uuid
  - brick
  - vty
  - http-conduit
  - resourcet
  - attoparsec
  - mtl

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints
  - -threaded

library:
  source-dirs: lib

executables:
  tic-tac-toe:
    main: tic-tac-toe.hs
    source-dirs: app
    dependencies:
      - small-games

  rock-paper-scissors:
    main: rock-paper-scissors.hs
    source-dirs: app
    dependencies:
      - small-games
      
  server:
    main: server.hs
    source-dirs: app

  tui-client:
    main: tui-client.hs
    source-dirs: app
    # dependencies:
    #   - small-games